### ISSUE TITLE
Testo presentazione applicazione

### ISSUE THREAD

**Issue by fschtn** [francescosche/Progetto-RC#14]
https://github.com/francescosche/Progetto-RC/blob/818652f05a55852db987cf9272b9122b9e5b1f33/files/index.html#L18

Sostituire con un testo di presentazione dell'applicazione, così da far capire all'utente a cosa sta facendo l'accesso, spiegando magari le funzionalità base.

**Comment by fschtn** [comment]
@mentelmarian , @MarcoGorga idee? 👍

**Comment by MarcoGorga** [comment]
<< [nome applicazione] è l'applicazione perfetta per tutti gli amanti della lettura. D'ora in avanti potrai:
      - Tener traccia di tutti i libri che hai letto
      - Creare una lista dei libri che hai intenzione di leggere prossimamente
      - Non dimenticherai più la pagina a cui sei arrivato/a con la comoda funzione segnalibro
      e inoltre potrai tenere d'occhio i progressi dei tuoi amici di Facebook
>>

Qualcosa del genere...

**Comment by fschtn** [comment]
Perfetto!
A me piace anche così 👍 

Per quanto riguarda **[nome applicazione]** io per ora ho scritto "_Book time_", se avete idee migliori, c'è sempre tempo per modificarlo 😄

**Comment by mentelmarian** [comment]
Si, la descrizione la approvo anche io. Anche io titolo va bene per me. Volendo quello col tempo si può cambiare se troviamo qualcosa di meglio

**Comment by MarcoGorga** [comment]
Era solo una bozza ma se vi piace la teniamo così ahahah
Allora il titolo lasciamo "Book Time" per ora, poi se ci viene qualche idea migliore in mente lo cambiamo in corso d'opera

**Comment by fschtn** [comment]
Ottimo, inserito e _pushato_, passo e chiudo! 🔥
