### ISSUE TITLE
Trovare idea progetto

### ISSUE THREAD

**Issue by fschtn** [francescosche/Progetto-RC#2]
Bisogna trovare un'idea per il progetto così da avviarne lo sviluppo

**Comment by fschtn** [comment]
Oh, ma tipo un programmino che, quando si mette like a un video musicale su YouTube, lo aggiunge (se lo trova) in automatico a una playlist di Spotify?

**Comment by mentelmarian** [comment]
Roba seria. Dici che si può fare?

**Comment by fschtn** [comment]
Leggendo le [API di Spotify](https://developer.spotify.com/web-api/add-tracks-to-playlist/) e [quelle di YouTube](https://developers.google.com/youtube/v3/docs/activities/list), penso di si..

Ma Marco si è registrato a GitHub?

**Comment by mentelmarian** [comment]
Non penso l'abbia fatto

**Comment by fschtn** [comment]
Perfetto, oggi glielo ricordo 😂

**Comment by francescosche** [comment]
Hola @MarcoGorga !
Idee?

**Comment by fschtn** [comment]
Apposto, ricapitolando il discorso di prima in aula:

Applicazione che, una volta eseguito il login con Facebook e Google, mostra un profilo utente che riepiloga:

- I libri in corso di lettura
- I libri in coda di lettura
- I libri letti dall'utente

Dal profilo si può arrivare anche a una pagina dedicata alle statistiche dell'utente (che vedremo in seguito) o alla pagina degli amici, su cui viene mostrato un elenco di amici che hanno utilizzato l'applicazione e da cui è possibile raggiungere ciascun profilo.

E' anche possibile cercare nuovi libri tramite la barra di ricerca.

Tutti i libri verranno cercati su [Google Books](https://developers.google.com/books/), tramite il token ottenuto dall'account Google dell'utente al momento del login.

Tutti gli amici che hanno eseguito l'accesso all'app verranno invece ricercati tramite le [API di Facebook](https://developers.facebook.com/docs/graph-api/).
