### ISSUE TITLE
Grafica lato client

### ISSUE THREAD

**Issue by fschtn** [francescosche/Progetto-RC#8]
@mentelmarian @MarcoGorga , ma se facessimo la grafica tutta da lato client su browser, il prof ha intenzione di chiedere informazioni?

Perché nel caso potrei farmi io tutta la grafica e la gestione da lato client, che interroga poi i file NodeJS che sviluppiamo insieme (y)

**Comment by MarcoGorga** [comment]
In realtà il professore ha detto più volte che la grafica sarebbe solo un plus inutile in quanto non è oggetto di questo corso

**Comment by fschtn** [comment]
Perfetto!
Che faccio, chiedo comunque conferma su Piazza?

Perché comunque una parte del codice sarà scritta nell'HTML, anche se poi non fa altro che "integrare" i file JS che scriveremo

**Comment by mentelmarian** [comment]
Da parte mia va bene, si può anche fare

**Comment by fschtn** [comment]
Apposto, alla domani mattina vedo di mettermi a fare qualcosa, buonanotte 😴
